Update to 1.80 with tables
inkyblackness/imgui-go pull request #138
Opened 2021-01-30 19:32 UTC by the-goodies

Rather large update. I have been using tables since ~summer and they work really well.

2021-01-30 20:31 UTC, the-goodies commented
Fixed all linters errors. Still fails due the fact that version is 1.80 and not 1.79.

2021-02-08 16:39 UTC, dertseha commented
Thank you for the effort.
May I ask you to prepare the related changes as well - such as adapting the test, readme, and screenshot?

2021-02-08 19:33 UTC, the-goodies commented
Should be good to go. For some reason, I assumed that only you can fix those test issues 😆

2021-02-13 19:55 UTC, the-goodies commented
Updated to 1.81 version. Some potentially braking changes to freetype font rendering.

2021-02-14 08:50 UTC, dertseha requested changes
I've done a first pass of a review. Seems like this change will cause yet another bump of the major version, there are several breaking changes.

Please address my comments - I'll then do the final steps.

2021-02-14 08:50 UTC, dertseha commented on IO.go
> +func (io IO) SetConfigDragClickToInputText(value bool) {
Is this function mandatory? If it's marked "beta", then it might change, causing yet another major version bump for the wrapper.

2021-02-14 08:50 UTC, dertseha commented on Tables.go
> +// Tables: Headers & Columns declaration
I don't think such free-floating comment blocks are included in the generated documentation.
Perhaps add these blocks to a prominent "first" function for the respective functionality.

2021-02-14 08:50 UTC, dertseha commented on Widgets.go
> +// Legacy Columns API (2020: prefer using Tables!)
Add this block to `Columns()` documentation.

2021-02-15 19:16 UTC, dertseha approved these changes
Perfect, thank you!

2021-02-15 19:16 UTC, merged